config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :auths, controllers: { confirmations: 'users/confirmations', sessions: 'sessions' }

  root 'master_admins/dashboard#index', as: :authenticated_root

  namespace :master_admins, path: 'admin', as: :admin do
    resources :companies do
      member do
        get :logisticians
      end
    end
    resources :trailers do
      resources :access_permissions, shallow: true
      resources :cameras, shallow: true, controller: 'trailer_cameras', only: %i[index] do
        patch :enable
        patch :disable
      end
    end
    resources :logisticians do
      member do
        patch :assign_trailer
        patch :unassign_trailer
      end
    end
    resources :custom_routes
    resources :drivers
  end

  namespace :api, format: :json do
    namespace :v1 do
      scope module: :trailers do
        resources :sensors do
          scope module: :sensors do
            resources :events, only: :index
          end
        end
      end

      resource :logistician, controller: :logistician, only: %i[update show] do
        collection do
          patch :update_password
        end
      end

      resources :trailers, only: %i[show index] do
        member do
          patch :update_status
          patch :read_status
        end

        scope module: :trailers do
          resources :route_logs, only: :index, path: :route_log
          resources :events, only: %[index], shallow: true do
            member { patch :resolve_alarm }
          end
          resources :media, only: :index do
            collection do
              post :request_media
            end
          end
          resources :sensors, only: :index
        end
      end

      resources :sensor_settings, only: :update
      resources :people, only: :index

      mount_devise_token_auth_for 'Auth', at: 'auth', skip: %i[omniauth_callbacks], controllers: {
        sessions:  'overrides/sessions',
        token_validations: 'overrides/token_validations'
      }
    end

    namespace :safeway do
      resources :media, param: :uuid, only: [] do
        member do
          post :upload
          post :failure
        end
      end
    end
  end

  require 'sidekiq/web'
  authenticate :auth, lambda { |auth| auth.master_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/master_admin.rb
class MasterAdmin < ApplicationRecord
  has_one :auth, dependent: :destroy
end

app/controllers/master_admins/access_permissions_controller.rb
class MasterAdmins::AccessPermissionsController < MasterAdmins::BaseController
  def index
    trailer = ::Trailer.find(params[:trailer_id])
    render :index, locals: {
      permissions: trailer.access_permissions.joins(:logistician).merge(::Logistician.active),
      trailer: ::TrailerPresenter.new(trailer)
    }
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_trailers_path, alert: t('master_admins.access_permissions.not_found')
  end

  def new
    trailer = ::Trailer.find(params[:trailer_id])
    render :new, locals: form_locals(trailer.access_permissions.new)
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_trailers_path, alert: t('master_admins.access_permissions.not_found')
  end

  def edit
    permission = ::TrailerAccessPermission.find(params[:id])
    render :edit, locals: form_locals(permission)
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_trailers_path, alert: t('master_admins.access_permissions.not_found')
  end

  def create
    grant = ::MasterAdmin::Trailer::AccessPermission::Grant.new
    grant.call(access_permission_params) do |m|
      m.success do
        redirect_to admin_logistician_path(access_permission_params[:logistician_id]), notice: t('.success')
      end

      m.failure(:logistician_not_found) do
        redirect_to admin_logisticians_path, alert: t('master_admins.logisticians.not_found')
      end

      m.failure(:trailer_not_found) do
        redirect_to admin_logistician_path(access_permission_params[:logistician_id]),
          alert: t('master_admins.trailers.not_found')
      end

      m.failure do |result|
        @errors = result[:errors]
        render :new, locals: form_locals(result[:permission])
      end
    end
  end

  def update
    update = ::MasterAdmin::Trailer::AccessPermission::Update.new
    update.call(access_permission_params) do |m|
      m.success do
        redirect_to admin_logistician_path(access_permission_params[:logistician_id]), notice: t('.success')
      end

      m.failure(:logistician_not_found) do
        redirect_to admin_logisticians_path, alert: t('master_admins.logisticians.not_found')
      end

      m.failure(:permission_not_found) do
        redirect_to admin_logistician_path(access_permission_params[:logistician_id]),
          alert: t('master_admins.access_permissions.not_found')
      end

      m.failure do |result|
        @errors = result[:errors]
        render :edit, locals: form_locals(result[:permission])
      end
    end
  end

  private

  def form_locals(permission)
    logistician = ::Logistician.active.find(
      params[:logistician_id].presence || access_permission_params[:logistician_id]
    )
    {
      permission: permission,
      trailer_presenter: TrailerPresenter.new(permission.trailer),
      logistician_presenter: LogisticianPresenter.new(logistician)
    }
  end

  def access_permission_params
    params
      .require(:trailer_access_permission)
      .permit(
        %i[
          logistician_id sensor_access event_log_access alarm_control
          system_arm_control load_in_mode_control photo_download
          video_download monitoring_access current_position route_access
          alarm_resolve_control
        ]
      )
      .merge(
        params.permit(%i[id trailer_id logistician_id])
      )
  end
end

app/controllers/master_admins/base_controller.rb
class MasterAdmins::BaseController < ApplicationController
  layout 'master_admin'

  before_action :authenticate_auth!
  before_action :authenticate_admin

  include ::ErrorHelper

  private

  def authenticate_admin
    return render json: { error: 'Access denied' } unless current_auth.master_admin_id?
  end
end

app/controllers/master_admins/companies_controller.rb
class MasterAdmins::CompaniesController < MasterAdmins::BaseController
  def new
    render :new, locals: { company: ::Company.new }
  end

  def create
    ::MasterAdmin::Company::Register.new.call(company_params) do |r|
      r.success { |_| return redirect_to admin_companies_path, notice: t('.success') }
      r.failure { |monad| @errors = monad[:errors] }
    end

    render :new, locals: { company: ::Company.new(company_params) }
  end

  def edit
    company = ::Company.active.find(params[:id])
    render :edit, locals: { company: company }
  end

  def update
    ::MasterAdmin::Company::Update.new.call(update_company_params) do |r|
      r.success { |_| return redirect_to admin_companies_path, notice: t('.success') }
      r.failure(:company_not_found) do
        return redirect_to admin_companies_path, alert: t('master_admins.companies.not_found')
      end
      r.failure { |monad| @errors = monad[:errors] }
    end

    company = ::Company.active.find(params[:id])
    company.assign_attributes(company_params)
    render :edit, locals: { company: company }
  end

  def index
    companies = ::CompanyPresenter.wrap(::Company.active)
    render :index, locals: { companies: companies }
  end

  def destroy
    ::MasterAdmin::Company::Archive.new.call(params[:id]) do |r|
      r.success do |_|
        redirect_to admin_companies_path, notice: t('.success')
      end
      r.failure(:company_not_found) do |_|
        redirect_to admin_companies_path, alert: t('master_admins.companies.not_found')
      end
    end
  end

  def logisticians
    company = ::Company.find(params[:id])
    logisticians = ::LogisticianPresenter.wrap(company.logisticians.includes(:auth, :person).active)
    render :logisticians, locals: { company: ::CompanyPresenter.new(company), logisticians: logisticians }
  end

  private

  def company_params
    params.require(:company).permit(:name, :email, :nip, :city, :street, :postal_code, :email)
  end

  def update_company_params
    company_params.merge(id: params[:id])
  end
end

app/controllers/master_admins/custom_routes_controller.rb
class MasterAdmins::CustomRoutesController < MasterAdmins::BaseController
  def new
    render :new, locals: { trailer_options: ::Trailer.active.pluck(:registration_number, :id) }
  end

  def create
    import = ::MasterAdmin::RouteLog::ImportFromGpx.new
    import.call(import_params) do |m|
      m.success do
        redirect_to new_admin_custom_route_path, notice: t('.success')
      end

      m.failure(:trailer_not_found) do
        redirect_to new_admin_custom_route_path, alert: t('master_admins.trailers.not_found')
      end

      m.failure do |res|
        @errors = res[:errors]
        new
      end
    end
  end

  private

  def import_params
    params.permit(:trailer_id, :file)
  end
end

app/controllers/master_admins/dashboard_controller.rb
class MasterAdmins::DashboardController < MasterAdmins::BaseController
  def index; end
end

app/controllers/master_admins/drivers_controller.rb
class MasterAdmins::DriversController < MasterAdmins::BaseController
  def index
    drivers = ::Driver.includes(person: :company).active
    render :index, locals: { drivers: drivers }
  end

  def new
    render :new, locals: form_locals
  end

  def create
    create = ::MasterAdmin::Driver::Create.new
    create.call(driver_params) do |m|
      m.success do
        redirect_to admin_drivers_path, notice: t('.success')
      end

      m.failure(:company_not_found) do
        redirect_to admin_drivers_path, alert: t('master_admins.companies.not_found')
      end

      m.failure do |result|
        @errors = result[:errors]
        render :new, locals: form_locals(result[:attributes])
      end
    end
  end

  def edit
    driver = ::Driver.find(params[:id])
    render :edit, locals: form_locals(driver)
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_drivers_path, alert: t('master_admins.drivers.not_found')
  end

  def update
    update = ::MasterAdmin::Driver::Update.new
    update.call(driver_params) do |m|
      m.success do
        redirect_to admin_drivers_path, notice: t('.success')
      end

      m.failure(:company_not_found) do
        redirect_to admin_drivers_path, alert: t('master_admins.companies.not_found')
      end

      m.failure(:driver_not_found) do
        redirect_to admin_drivers_path, alert: t('master_admins.drivers.not_found')
      end

      m.failure do |result|
        @errors = result[:errors]
        render :edit, locals: form_locals(result[:driver])
      end
    end
  end

  def destroy
    ::Driver.destroy(params[:id])
    redirect_to admin_drivers_path, notice: t('.success')
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_drivers_path, alert: t('master_admins.drivers.not_found')
  end

  private

  def form_locals(driver_attributes = {})
    driver = driver_attributes.is_a?(::Driver) ? driver_attributes : ::Driver.new(driver_attributes)
    { driver: driver, companies: ::Company.active.pluck(:name, :id) }
  end

  def driver_params
    params.require(:driver).permit(
      person_attributes: %i[first_name last_name phone_number extra_phone_number company_id email avatar]
    ).merge(id: params[:id])
  end
end

app/controllers/master_admins/logisticians_controller.rb
class MasterAdmins::LogisticiansController < MasterAdmins::BaseController
  def new
    logistician = ::Logistician.new
    companies   = ::Company.active.pluck(:name, :id)
    render :new, locals: { logistician: logistician, companies: companies }
  end

  def create
    register = ::MasterAdmin::Logistician::Register.new
    register.call(logistician_params) do |r|
      r.success { return redirect_to new_admin_logistician_path, notice: t('.success') }
      r.failure(:not_found) do
        return redirect_to admin_logisticians_path, alert: t('master_admins.logisticians.not_found')
      end
      r.failure { |monad| @errors = monad[:errors] }
    end

    logistician = ::Logistician.new(logistician_params)
    companies = ::Company.active.pluck(:name, :id)
    render :new, locals: { logistician: logistician, companies: companies }
  end

  def edit
    logistician = ::Logistician.active.find(params[:id])
    companies = ::Company.active.pluck(:name, :id)
    render :edit, locals: { logistician: logistician, companies: companies }
  end

  def update
    update = ::MasterAdmin::Logistician::Update.new
    update.call(logistician_params) do |r|
      r.success { return redirect_to admin_logisticians_path, notice: t('.success') }
      r.failure(:logistician_not_found) do
        return redirect_to admin_logisticians_path, alert: t('master_admins.logisticians.not_found')
      end
      r.failure(:company_not_found) do
        return redirect_to admin_logisticians_path, alert: t('master_admins.companies.not_found')
      end
      r.failure { |monad| @errors = monad[:errors] }
    end

    logistician = ::Logistician.active.find(params[:id])
    logistician.assign_attributes(logistician_params)
    # fails when provided country is not present in enum
    companies = ::Company.active.pluck(:name, :id)
    render :edit, locals: { logistician: logistician, companies: companies }
  end

  def index
    logisticians = ::LogisticianPresenter.wrap(::Logistician.includes(:auth, person: :company).active)
    render :index, locals: { logisticians: logisticians }
  end

  def show
    logistician = ::Logistician.active.find(params[:id])
    assigned_trailers = logistician.trailers.active.includes(:company)
    unassigned_trailers = ::Trailer
      .includes(:company)
      .active
      .where(company_id: logistician.person.company.id)
      .where.not(id: assigned_trailers.pluck(:id))
    assigned_trailers = ::TrailerPresenter.wrap(assigned_trailers)
    unassigned_trailers = ::TrailerPresenter.wrap(unassigned_trailers)
    logistician = ::LogisticianPresenter.new(logistician)

    render :show, locals: {
      assigned_trailers: assigned_trailers,
      unassigned_trailers: unassigned_trailers,
      logistician: logistician
    }
  end

  def unassign_trailer
    ::MasterAdmin::Logistician::UnassignTrailer.new.call(trailer_management_params) do |r|
      r.success do
        return redirect_to admin_logistician_path(params[:id]), notice: t('.success')
      end
      r.failure(:logistician_not_found) do
        return redirect_to admin_logisticians_path, alert: t('master_admins.logisticians.not_found')
      end
      r.failure(:trailer_not_found) do
        return redirect_to admin_logisticians_path, alert: t('master_admins.trailers.not_found')
      end
    end

    logistician = ::Logistician.active.find(params[:id])
    render :show, locals: { logistician: logistician }
  end

  def destroy
    ::MasterAdmin::Logistician::Archive.new.call(params[:id]) do |r|
      r.success do
        redirect_to admin_logisticians_path, notice: t('.success')
      end
      r.failure(:logistician_not_found) do
        redirect_to admin_logisticians_path, alert: t('master_admins.logisticians.not_found')
      end
    end
  end

  private

  def trailer_management_params
    params.permit(:id, :trailer_id)
  end

  def logistician_params
    params.require(:logistician).permit(
      :preferred_locale,
      person_attributes: %i[first_name last_name phone_number extra_phone_number company_id email avatar]
    ).merge(id: params[:id])
  end
end

app/controllers/master_admins/trailer_cameras_controller.rb
class MasterAdmins::TrailerCamerasController < MasterAdmins::BaseController
  def index
    trailer = ::Trailer.find(params[:trailer_id])
    render :index, locals: { cameras: trailer.cameras.order(:camera_type) }
  rescue ActiveRecord::RecordNotFound
    redirect_to admin_trailers_path, alert: t('master_admins.trailer_cameras.not_found')
  end

  def enable
    cmd = ::MasterAdmin::Trailer::Camera::Enable.new
    cmd.call(params[:camera_id]) do |m|
      m.success do |r|
        redirect_to admin_trailer_cameras_path(r.trailer_id), notice: t('master_admins.trailer_cameras.enabled')
      end

      m.failure(:not_found) do
        redirect_to admin_trailers_path, alert: t('master_admins.trailer_cameras.not_found')
      end
    end
  end

  def disable
    cmd = ::MasterAdmin::Trailer::Camera::Disable.new
    cmd.call(params[:camera_id]) do |m|
      m.success do |r|
        redirect_to admin_trailer_cameras_path(r.trailer_id), notice: t('master_admins.trailer_cameras.disabled')
      end

      m.failure(:not_found) do
        redirect_to admin_trailers_path, alert: t('master_admins.trailer_cameras.not_found')
      end
    end
  end
end

app/helpers/master_admin/locales_helper.rb
module MasterAdmin::LocalesHelper
  def locales_to_select(locales)
    locales.keys.map { |locale| [I18n.t("languages.#{locale}"), locale] }
  end
end

app/views/master_admins/access_permissions/_form_fields.html.haml
= f.hidden_field :logistician_id, value: logistician_id

.field
  .control
    = f.label :sensor_access, class: 'admin-label label' do
      = f.check_box :sensor_access, {}, 'true', 'false'
      = f.label :sensor_access

.field
  .control
    = f.label :alarm_control, class: 'admin-label label' do
      = f.check_box :alarm_control, {}, 'true', 'false'
      = f.label :alarm_control

.field
  .control
    = f.label :alarm_resolve_control, class: 'admin-label label' do
      = f.check_box :alarm_resolve_control, {}, 'true', 'false'
      = f.label :alarm_resolve_control

.field
  .control
    = f.label :system_arm_control, class: 'admin-label label' do
      = f.check_box :system_arm_control, {}, 'true', 'false'
      = f.label :system_arm_control

.field
  .control
    = f.label :load_in_mode_control, class: 'admin-label label' do
      = f.check_box :load_in_mode_control, {}, 'true', 'false'
      = f.label :load_in_mode_control

.field
  .control
    = f.label :photo_download, class: 'admin-label label' do
      = f.check_box :photo_download, {}, 'true', 'false'
      = f.label :photo_download

.field
  .control
    = f.label :video_download, class: 'admin-label label' do
      = f.check_box :video_download, {}, 'true', 'false'
      = f.label :video_download

.field
  .control
    = f.label :monitoring_access, class: 'admin-label label' do
      = f.check_box :monitoring_access, {}, 'true', 'false'
      = f.label :monitoring_access

.field
  .control
    = f.label :current_position, class: 'admin-label label' do
      = f.check_box :current_position, {}, 'true', 'false'
      = f.label :current_position

.field
  .control
    = f.label :route_access, class: 'admin-label label' do
      = f.check_box :route_access, {}, 'true', 'false'
      = f.label :route_access

.field
  .control
    = f.label :event_log_access, class: 'admin-label label' do
      = f.check_box :event_log_access, {}, 'true', 'false'
      = f.label :event_log_access

.field
  .control
    = f.submit submit_text, class: 'button is-primary'

app/views/master_admins/access_permissions/_form_header.haml
%section.section
  %h2.subtitle
    #{t('.logistician')}: #{logistician_presenter.full_name}
  %p
    #{t('.device_serial_number')}: #{trailer_presenter.device_serial_number}
  %p
    #{t('.registration_number')}: #{trailer_presenter.registration_number}
  %p
    #{t('.phone_number')}: #{trailer_presenter.phone_number}
  %p
    #{t('.company')}: #{trailer_presenter.company}

app/views/master_admins/access_permissions/edit.haml
= render 'form_header',
  logistician_presenter: logistician_presenter,
  trailer_presenter: trailer_presenter

%section.section
  %h2.subtitle= t('master_admins.access_permissions.title')

  = form_for [:admin, permission], url: admin_access_permission_path do |f|
    = render 'form_fields',
      f: f,
      logistician_id: logistician_presenter.id,
      submit_text: t('form.update')

app/views/master_admins/access_permissions/index.haml
%section.section
  %h1.title= t('master_admins.access_permissions.title')
  %h2.subtitle
    #{t('.company')}: #{trailer.company}
  %p
    #{t('.device_serial_number')}: #{trailer.device_serial_number}
  %p
    #{t('.registration_number')}: #{trailer.registration_number}
  %p
    #{t('.phone_number')}: #{trailer.phone_number}


%section.section
  %table.table.is-hoverable.admin-permissions-table
    %thead
      %th= t('.logistician')
      %th= t('.sensor_access')
      %th= t('.event_log_access')
      %th= t('.alarm_control')
      %th= t('.alarm_resolve_control')
      %th= t('.system_arm_control')
      %th= t('.load_in_mode_control')
      %th= t('.photo_download')
      %th= t('.video_download')
      %th= t('.monitoring_access')
      %th= t('.current_position')
      %th= t('.route_access')
      %th
    %tbody
      - permissions.each do |permission|
        %tr
          %td= permission.logistician.person.first_name
          %td
            %span
              %i{ class: check_icon_class(permission.sensor_access) }
          %td
            %span
              %i{ class: check_icon_class(permission.event_log_access) }
          %td
            %span
              %i{ class: check_icon_class(permission.alarm_control) }
          %td
            %span
              %i{ class: check_icon_class(permission.alarm_resolve_control) }
          %td
            %span
              %i{ class: check_icon_class(permission.system_arm_control) }
          %td
            %span
              %i{ class: check_icon_class(permission.load_in_mode_control) }
          %td
            %span
              %i{ class: check_icon_class(permission.photo_download) }
          %td
            %span
              %i{ class: check_icon_class(permission.video_download) }
          %td
            %span
              %i{ class: check_icon_class(permission.monitoring_access) }
          %td
            %span
              %i{ class: check_icon_class(permission.current_position) }
          %td
            %span
              %i{ class: check_icon_class(permission.route_access) }
          %td
            = link_to t('.edit'),
              edit_admin_access_permission_path(id: permission.id, logistician_id: permission.logistician.id)

app/views/master_admins/access_permissions/new.haml
= render 'form_header',
  logistician_presenter: logistician_presenter,
  trailer_presenter: trailer_presenter

%section.section
  %h2.subtitle= t('master_admins.access_permissions.title')

  = form_for [:admin, permission] do |f|
    = render 'form_fields',
      f: f,
      logistician_id: logistician_presenter.id,
      submit_text: t('form.create')