config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :auths, controllers: { confirmations: 'users/confirmations', sessions: 'sessions' }

  root 'master_admins/dashboard#index', as: :authenticated_root

  namespace :master_admins, path: 'admin', as: :admin do
    resources :companies do
      member do
        get :logisticians
      end
    end
    resources :trailers do
      resources :access_permissions, shallow: true
      resources :cameras, shallow: true, controller: 'trailer_cameras', only: %i[index] do
        patch :enable
        patch :disable
      end
    end
    resources :logisticians do
      member do
        patch :assign_trailer
        patch :unassign_trailer
      end
    end
    resources :custom_routes
    resources :drivers
  end

  namespace :api, format: :json do
    namespace :v1 do
      scope module: :trailers do
        resources :sensors do
          scope module: :sensors do
            resources :events, only: :index
          end
        end
      end

      resource :logistician, controller: :logistician, only: %i[update show] do
        collection do
          patch :update_password
        end
      end

      resources :trailers, only: %i[show index] do
        member do
          patch :update_status
          patch :read_status
        end

        scope module: :trailers do
          resources :route_logs, only: :index, path: :route_log
          resources :events, only: %[index], shallow: true do
            member { patch :resolve_alarm }
          end
          resources :media, only: :index do
            collection do
              post :request_media
            end
          end
          resources :sensors, only: :index
        end
      end

      resources :sensor_settings, only: :update
      resources :people, only: :index

      mount_devise_token_auth_for 'Auth', at: 'auth', skip: %i[omniauth_callbacks], controllers: {
        sessions:  'overrides/sessions',
        token_validations: 'overrides/token_validations'
      }
    end

    namespace :safeway do
      resources :media, param: :uuid, only: [] do
        member do
          post :upload
          post :failure
        end
      end
    end
  end

  require 'sidekiq/web'
  authenticate :auth, lambda { |auth| auth.master_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/partials/_errors.haml
- if @errors
  .notification.is-danger
    %ul
      - formatted_errors(@errors).each do |msg|
        %li= msg

app/views/layouts/partials/_flash.html.haml
- if notice
  .notification.is-success
    = notice

- if alert
  .notification.is-danger
    = alert

app/views/layouts/partials/_sidebar.html.haml
.is-two-fifths
  %aside.menu.navbar-border
    %ul.menu-list
      %li
        %b= t('.manage_companies')
        %ul
          %li= link_to t('.companies'), admin_companies_path
          %li= link_to t('.create_company'), new_admin_company_path

      %li
        %b= t('.manage_logisticians')
        %ul
          %li= link_to t('.logisticians'), admin_logisticians_path
          %li= link_to t('.create_logistician'), new_admin_logistician_path

      %li
        %b= t('.manage_trailers')
        %ul
          %li= link_to t('.trailers'), admin_trailers_path
          %li= link_to t('.create_trailer'), new_admin_trailer_path

      %li
        %b= t('.manage_drivers')
        %ul
          %li= link_to t('.drivers'), admin_drivers_path
          %li= link_to t('.create_driver'), new_admin_driver_path

      %li
        %b= t('.account_settings')
        %ul
          %li= link_to t('.sign_out'), destroy_auth_session_path, method: :delete